### ISSUE TITLE
[discussion] enable custom config for each project

### ISSUE THREAD

**Issue by ClemensSahs** [Siilwyn/css-declaration-sorter-atom#113] opened 2020-10-05 09:08 UTC
Here I write some ideas for the feature custom config file, this is a next evolution for #109

**naming**
- postcss-sorting.json (like https://github.com/lysyi3m/atom-postcss-sorting)
- use package.json option "postcssSortingConfig"

**paths**
- `~/`
- `currentProjectDir/`

**Comment by Siilwyn** [comment] 2020-10-05 16:46
I think this is a duplicate of #49?

I think to start with one file in the current project directory makes the most sense, don't want to read files outside of your project. Perhaps a `css-declaration-sorter-atom.json` file?

Personally not a huge fan of this feature either way since it makes more sense to do this in a dev/build npm script using the postcss cli and [css-declaration-sorter](https://github.com/Siilwyn/css-declaration-sorter/) directly.

**Comment by ClemensSahs** [comment] 2020-10-05 18:41
> I think this is a duplicate of #49?

Is fixed with #109 in my mind

> I think to start with one file in the current project directory makes the most sense, don't want to read files outside of your project.  

Yes thats why I want a discussion over the possible points ;)

> Perhaps a `css-declaration-sorter-atom.json` file?

in My mind `package.json` is the best point. But I think we need a second/fallback file for the case that a user don't use npm/yarn. And `css-declaration-sorter-atom.json` is more focus on our/you project. I'm a fan of much generic naming as possible. (Like PSR and framework cooperate)
We use postcss and are a sorter. If `postcss-sorting.json` to much similar to `atom-postcss-sorting`.
I will propose `postcss-sorter.json` as fallback file.

> Personally not a huge fan of this feature either way since it makes more sense to do this in a dev/build npm script using the postcss cli and [css-declaration-sorter](https://github.com/Siilwyn/css-declaration-sorter/) directly.

Yes I now, but this is not in any case possible. I prefer githook `pre-commit` for this. But in some project we are not able to refactor everything. ;)

**Comment by Siilwyn** [comment] 2020-10-06 19:46
What do you think of `css-declaration-order.json`?
It's very descriptive of the content and as far as I can see doesn't conflict with other extensions.

**Closed** 2021-08-11 14:53 UTC
